### PR TITLE
Improve error messages on the frontend and for misconfigured environments

### LINKED ISSUE #27: Create improved error messages when things fail
When requests go wrong on the backend, implement better error messages. Examples include when `password != confirm_password`, when a user tries to log in with poor credentials, and other use cases.

Also, improve error messages for when the user's environment is improperly configured.

### PR DESCRIPTION
**Pull request by zbreit**
Closes #27. Should wait until #24 is merged

### CODE REVIEW

**Comment by SamuelHoward** [comment]
The error messages for missing environment variables are super helpful. The explicit listing of the missing variable definitions is great.

**Comment by zbreit** [comment]
@SamuelHoward @jonahtash Everything w/ the stored procs should be up and running. The code is all functional now if you have the correct environment variables set up.

**Comment by SamuelHoward** [comment]
I like the frontend warnings I'm seeing, but the missing environment error messages seem to be broken on my end. Maybe I'm doing something wrong, but now I get this error if any number of my environment variables are missing (rather than seeing the list of missing variables): 
PASS-7-23-2020_0
I don't understand this error, but the flask app runs successfully if I have the environment variables properly defined.

**Comment by zbreit** [comment]
Hmmm, that's interesting... We'll have to look into that issue at today's meeting. Try pulling the most recent changes and see if that helps.

**Comment by zbreit** [comment]
I figured out the actual issue: I was using an iterator whose values had already been depleted, so it recognize missing environment variables, but wouldn't print them :(

**Comment by SamuelHoward** [comment]
Looks good on my end now.

**Pull request merged**
